name: op_py311
channels:
  - conda-forge
  - pytorch
  # - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - typing-extensions >=4.8.0
  - numpy=1.23 # pygamを使えない
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  # - pytorch-cuda=12.4 -> 推論のみなのでGPU不要
  - lightgbm
  - pygam
  - huggingface_hub
  - tqdm
  - pyyaml
  # - jupyterlab
  # - ipykernel
  # - notebook
  # - ipywidgets
  - sqlalchemy
  - chardet
  - plotly
  - streamlit
  - openpyxl
  - pip:
      # - mlflow==2.17
      # - hydra-core
      - requests
      - mip
      - pulp
      - jpholiday
      - cvxopt
      - playwright
      - highspy # condaではエラーになる
      - pyomo